apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}
    labels:
        app: {{ .Values.name }}
spec:
    ports:
        - name: {{ .Values.name }}
          port: 8097
          protocol: TCP
          targetPort: 8097
    selector:
        app: {{ .Values.name }}
    type: ClusterIP
